services:
  nginx-proxy:
    image: nginx:alpine
    container_name: simple-nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true
